# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tabularml',
                'doc_host': 'https://JaumeAmoresDS.github.io',
                'git_url': 'https://github.com/JaumeAmoresDS/tabularml',
                'lib_path': 'tabularml'},
  'syms': {}}
